---
- group: name={{ user }} state=present

- user: name={{ user }} group={{ user }} append=yes

- file: path={{ directory }}/.ssh
        state=directory
        mode=0755
        group={{ user }}
  become: yes
  become_user: "{{ user }}"

- file: path={{ directory }}/public
        state=directory
        mode=0755
        group={{ user }}
  become: yes
  become_user: "{{ user }}"

- name: create letsencrypt cert verification directory
  file: path={{ directory }}/public/.well-known
        state=directory
        mode=0755
        group={{ user }}
  become: yes
  become_user: "{{ user }}"

- name: create mysql user {{ database_user }}
  mysql_user: name={{ database_user }}
              password={{ database_password }}
              priv={{ database_name }}.*:ALL,GRANT
              login_host={{ database_host }}
              state=present

- name: ensure {{ database_name }} is present
  mysql_db: name={{ database_name }}
            state=present
            login_host={{ database_host }}
            login_password={{ database_password }}
            login_user={{ database_user }}

- name: check whether database is imported
  command: "/usr/bin/mysql --database={{ database_name }} --password={{ database_password }} --user={{ database_user }} --host={{ database_host }} --execute='show tables'"
  register: result

- include: import_database.yml
  when: result.stdout_lines | length == 0

- name: clone Wordpress
  git: repo={{ wordpress_url }}
       dest={{ directory }}/public
       version={{ wordpress_version }}
       depth=1
  become: yes
  become_user: "{{ user }}"

- name: copy wp-config.php into place
  template: src=wp-config.php
            dest={{ directory }}/public/wp-config.php
            owner={{ user }}
            group={{ user }}

- git: repo=https://github.com/kevinburke/2013.git
       dest={{ directory }}/public/wp-content/themes/flat-ui
  become: yes
  become_user: "{{ user }}"

- git: repo=https://github.com/kevinburke/syntaxhighlighter.git
       dest={{ directory }}/public/wp-content/plugins/syntaxhighlighter
  become: yes
  become_user: "{{ user }}"

- git: repo=https://github.com/kevinburke/tweets.git
       dest={{ directory }}/public/twitter
  become: yes
  become_user: "{{ user }}"

- name: install slides
  include: slides.yml

- name: install letter
  include: letter.yml

- template: src=nginx.conf
            dest={{ nginx_include_dir }}/{{ domain }}.conf
            owner=nginx
            group=nginx
  notify: reload nginx

- git: repo=https://github.com/kevinburke/blog.git
       dest={{ directory }}/public/rawblog
  become: yes
  become_user: "{{ user }}"

- name: copy etc deployment key to remote server
  copy: src={{ etc_private_key }} dest={{ etc_remote_private_key }} mode=0400
  become: yes
  become_user: "{{ user }}"

- git: repo=git@bitbucket.org:kevinburke/etc.git
       dest={{ directory }}/data
       key_file={{ etc_remote_private_key }}
       accept_hostkey=yes
  become: yes
  become_user: "{{ user }}"

- name: copy font deployment key to remote server
  copy: src={{ font_private_key }} dest={{ font_remote_private_key }} mode=0400
  become: yes
  become_user: "{{ user }}"

- git: repo=git@bitbucket.org:kevinburke/inburke_fonts.git
       dest={{ directory }}/public/font
       key_file={{ font_remote_private_key }}
       accept_hostkey=yes
  become: yes
  become_user: "{{ user }}"

- name: copy luxr deployment key to remote server
  copy: src={{ luxr_private_key }} dest={{ luxr_remote_private_key }} mode=0400
  become: yes
  become_user: "{{ user }}"

- git: repo=git@bitbucket.org:kevinburke/luxr_git.git
       dest={{ directory }}/public/luxr
       key_file={{ luxr_remote_private_key }}
       accept_hostkey=yes
  become: yes
  become_user: "{{ user }}"

- name: copy resume deployment key to remote server
  copy: src={{ resume_private_key }} dest={{ resume_remote_private_key }} mode=0400
  become: yes
  become_user: "{{ user }}"

- git: repo=git@bitbucket.org:kevinburke/resume.git
       dest={{ directory }}/public/resume
       key_file={{ resume_remote_private_key }}
       accept_hostkey=yes
  become: yes
  become_user: "{{ user }}"

- name: copy etc files into place
  # trailing slash after data is important
  command: 'rsync --archive --filter="- .git/" --filter="+ *" {{ directory }}/data/ {{ directory }}/public'
  become: yes
  become_user: "{{ user }}"


  # - /opt/letsencrypt/letsencrypt-auto certonly --webroot -w /home/athenian/public -d athenian.me --renew-by-default --email kev@inburke.com --text --agree-tosecome_user: "{{ user }}"
