---

- name: Install anonymouszen.net
  hosts: droplets

  roles:
    - role: anonymouszen.net
      anonymouszen_ssl_enabled: False
      wordpress_version: '4.6'

  vars_files:
    - roles/anonymouszen.net/vars/wordpress.yml
