---
- name: Install stage.inburke.com
  hosts: droplets

  roles:
    - role: inburke-blog
      user: stage
      directory: "/home/{{ user }}"
      domain: stage.inburke.com
      inburke_ssl_enabled: True
      php_file_directory: "/home/{{ user }}/public/"
      local_database_dump: databases/stage.dump.sql
      remote_database_dump: "{{ directory }}/tmp/stage.dump.sql"

  # This file is encrypted
  vars_files:
    - roles/stage.inburke.com/vars/wordpress.yml
