---
- name: Install stage.inburke.com
  hosts: droplets

  roles:
    - role: common

    # Variables for this role are encrypted / provided by vars_files below.
    - role: mysql_database
      user: stage
      directory: /home/stage

    - role: inburke-blog
      user: stage
      directory: "/home/{{ user }}"
      domain: stage.inburke.com
      inburke_ssl_enabled: True
      php_file_directory: "/home/{{ user }}/public/"
      wordpress_version: '4.8'
      redirect_domains:
        - www.stage.inburke.com
      syntaxhighlighter_version: 'develop'

  # This file is encrypted and includes
  # - database_user
  # - database_password
  #
  # etc etc
  vars_files:
    - roles/stage.inburke.com/vars/wordpress.yml

# /opt/certbot/certbot-auto  certonly --webroot -w /home/stage/public -d stage.inburke.com --renew-by-default --email kev@inburke.com --text --agree-tos
# /opt/certbot/certbot-auto  certonly --webroot -w /home/stage/public -d www.stage.inburke.com --renew-by-default --email kev@inburke.com --text --agree-tos
