#!/usr/bin/env bash

set -e

main() {
    local backup_file="summers-$(uname -n)-$(date +%Y-%m-%d_%H-%M-%S)"
    /usr/local/bin/tarsnap --print-stats -c \
        -f "$backup_file" /home/summers/public
}

main "$@"
