---
- group: name=burkeservices state=present

- user: name=burkeservices group=burkeservices append=yes

- template: src=nginx.conf
            dest={{ nginx_include_dir }}/burke.services.conf
            owner=nginx
            group=nginx
  notify: reload nginx

#- name: install SSL certificate
  #command: /opt/letsencrypt/letsencrypt-auto certonly --webroot -w /home/athenian/public -d athenian.me --renew-by-default --email kev@inburke.com --text --agree-tos

# - cron:
# - cron: ./letsencrypt-auto  certonly --webroot -w /home/athenian/public -d athenian.me --renew-by-default --email kev@inburke.com --text --agree-tos
