---
- group: name=burkeservices state=present

- user: name=burkeservices group=burkeservices append=yes

- git: repo=https://github.com/kevinburke/burke.services.git
       dest=/home/burkeservices/site
       depth=1
       version=1.1
  become: yes
  become_user: burkeservices

- template: src=nginx.conf
            dest={{ nginx_include_dir }}/burke.services.conf
            owner=nginx
            group=nginx
  notify: reload nginx

#- name: install SSL certificate
  #command: /opt/certbot/certbot-auto certonly --webroot -w /home/burkeservices/site/public -d burke.services --renew-by-default --email kev@inburke.com --text --agree-tos

# - cron: /opt/certbot/certbot-auto  certonly --webroot -w /home/burkeservices/site/public -d www.burke.services --renew-by-default --email kev@inburke.com --text --agree-tos
