---
wordpress_zip: "{{ directory }}/tmp/{{ wordpress_version }}.tar.gz"
wordpress_url: https://github.com/WordPress/WordPress.git
wordpress_debug: False
inburke_ssl_enabled: False
syntaxhighlighter_version: 'master'

akismet_version: '3.1.11'
akismet_url: "https://downloads.wordpress.org/plugin/akismet.{{ akismet_version }}.zip"

letter_private_key: ssh-keys/inburke.com/letter_rsa
letter_remote_private_key: "{{ directory }}/.ssh/letter_rsa"
etc_private_key: ssh-keys/inburke.com/etc_rsa
etc_remote_private_key: "{{ directory }}/.ssh/etc_rsa"
font_private_key: ssh-keys/inburke.com/font_rsa
font_remote_private_key: "{{ directory }}/.ssh/font_rsa"
luxr_private_key: ssh-keys/inburke.com/luxr_rsa
luxr_remote_private_key: "{{ directory }}/.ssh/luxr_rsa"
resume_private_key: ssh-keys/inburke.com/resume_rsa
resume_remote_private_key: "{{ directory }}/.ssh/resume_rsa"

inburke_theme_version: 1.4
