---
- group: name=kburkeorg state=present

- user: name=kburkeorg group=kburkeorg append=yes

- template: src=nginx.conf
            dest={{ nginx_include_dir }}/kburke.org.conf
            owner=nginx
            group=nginx
  notify: reload nginx

# These are blocked on inburke.com being set up

#- name: install SSL certificate
  #command: /opt/letsencrypt/letsencrypt-auto certonly --webroot -w /home/kburkeorg/public -d kburke.org --renew-by-default --email kev@inburke.com --text --agree-tos

# - cron:
# - cron: ./letsencrypt-auto  certonly --webroot -w /home/athenian/public -d athenian.me --renew-by-default --email kev@inburke.com --text --agree-tos
