---
# Instructions taken from https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Ubuntu

- name: get jenkins version
  shell: java -jar /usr/share/jenkins/jenkins.war --version
  register: result
  ignore_errors: True

- name: install jenkins
  include: install.yml
  when: result.rc != 0 or result.stdout_lines[2] != "{{ jenkins_version }}"

- name: create ssh directory
  file: path={{ jenkins_ssh_dir }} state=directory mode=0755
  become: yes
  become_user: jenkins

- name: copy jenkins deployment key to remote server
  copy: src={{ jenkins_private_key }} dest={{ jenkins_remote_private_key }} mode=0400
  become: yes
  become_user: jenkins

- template: src=ssh.config
            dest={{ jenkins_ssh_dir }}/config
            owner=jenkins
            group=jenkins

- template: src=jenkins.default
            dest=/etc/default/jenkins
            owner=jenkins
            group=jenkins
  notify: reload jenkins
