---
- group: name=go state=present

- user: name={{ user }} groups=go append=yes

- file: path="{{ directory }}/tmp"
        state=directory
        mode=0755
        group=go
  become: yes
  become_user: "{{ user }}"

- file: path={{ directory }}/tmp/go1.7
        state=directory
        mode=0755
        group=go
  become: yes
  become_user: "{{ user }}"

- unarchive: src=https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz
             dest={{ directory }}/tmp/go1.7
             copy=no
  become: yes
  become_user: "{{ user }}"

- file: path={{ directory }}/tmp/go1.7
        state=directory
        mode=0755
        group=go
  become: yes
  become_user: "{{ user }}"

- name: Move go1.7 directory into place
  command: cp -r {{ directory }}/tmp/go1.7/go {{ directory }}/go1.7
  args:
    creates: "{{ directory }}/go1.7"
  become: yes
  become_user: "{{ user }}"

- git: repo=https://go.googlesource.com/go
       dest={{ directory }}/go
       update=yes
  become: yes
  become_user: "{{ user }}"

- name: Install go tip
  command: ./make.bash
  args:
    chdir: "{{ directory }}/go/src"
    creates: "{{ directory }}/go/bin/go"
  environment:
    GOROOT_BOOTSTRAP: "{{ directory }}/go1.7"
    GOGC: 10
  become: yes
  become_user: "{{ user }}"
