---
- group: name=go state=present

- user: name={{ user }} groups=go append=yes

- file: path="{{ directory }}/tmp"
        state=directory
        mode=0755
        group=go
  become: yes
  become_user: "{{ user }}"

- file: path={{ directory }}/tmp/go1.4
        state=directory
        mode=0755
        group=go
  become: yes
  become_user: "{{ user }}"

- unarchive: src=https://storage.googleapis.com/golang/go1.4.3.src.tar.gz
             dest={{ directory }}/tmp/go1.4
             copy=no
  become: yes
  become_user: "{{ user }}"

- file: path={{ directory }}/tmp/go1.4
        state=directory
        mode=0755
        group=go
  become: yes
  become_user: "{{ user }}"

- name: Move go1.4 directory into place
  command: cp -r {{ directory }}/tmp/go1.4/go {{ directory }}/go1.4
  args:
    creates: "{{ directory }}/go1.4"
  become: yes
  become_user: "{{ user }}"

- name: Install go 1.4
  command: ./make.bash
  args:
    chdir: "{{ directory }}/go1.4/src"
    creates: "{{ directory }}/go1.4/bin/go"
  # https://github.com/golang/go/issues/13114#issuecomment-185931101
  environment:
    CGO_ENABLED: 0
  become: yes
  become_user: "{{ user }}"

- git: repo=https://go.googlesource.com/go
       dest={{ directory }}/go
       update=yes
  become: yes
  become_user: "{{ user }}"

- name: Install go tip
  command: ./make.bash
  args:
    chdir: "{{ directory }}/go/src"
    creates: "{{ directory }}/go/bin/go"
  environment:
    GOROOT_BOOTSTRAP: "{{ directory }}/go1.4"
    GOGC: 10
  become: yes
  become_user: "{{ user }}"
