---
- set_fact:
    open_basedirs="{{ open_basedirs }} + [ '{{ php_file_directory }}' ]"

- group: name=php state=present

- user: name=php group=php append=yes

- user: name=nginx groups=php append=yes

- name: get php version
  command: "/home/php/bin/php -r 'echo phpversion();' "
  register: result
  ignore_errors: True
  changed_when: result.rc != 0 or result.stdout != '{{ php_version }}'

- include: install.yml
  when: result.rc != 0 or result.stdout != '{{ php_version }}'

- file: path={{ php_home_dir }}/etc/fpm.d
        state=directory
        mode=0755
  become: yes
  become_user: php

# Needs to be writable by the php-fpm www processes, which run as the php user,
# or error_log will fail silently
- file: path={{ php_log_dir }}
        state=directory
        mode=0755
        owner=php
        group=php

- file: path={{ php_home_dir }}/run
        state=directory
        mode=0755
  become: yes
  become_user: php

- name: write the base php-fpm.conf
  template: src=php-fpm.conf
            dest={{ php_home_dir }}/etc/php-fpm.conf
            owner=php
            group=php
            mode=0644
  become: yes
  become_user: php
  notify: reload php

#- debug: var=open_basedirs

- name: write php.ini
  template: src=php.ini
            dest={{ php_home_dir }}/lib/php.ini
            owner=php
            group=php
            mode=0644
  become: yes
  become_user: php
  notify: reload php

- name: write /etc/init.d/php-fpm
  template: src=php-fpm.initd
            dest=/etc/init.d/php-fpm
            mode=0755
