---
- group: name=go state=present

- user: name={{ user }} groups=go append=yes

- file: path="{{ directory }}/tmp"
        state=directory
        mode=0755
        group=go
  become: yes
  become_user: "{{ user }}"

- name: "create path {{ directory }}/tmp"
  file: path={{ directory }}/tmp/{{ go_specific }}
        state=directory
        mode=0755
        group=go
  become: yes
  become_user: "{{ user }}"

- unarchive: src=https://storage.googleapis.com/golang/{{ go_specific }}.linux-amd64.tar.gz
             dest={{ directory }}/tmp/{{ go_specific }}
             copy=no
  become: yes
  become_user: "{{ user }}"

- name: Move {{ go_version }} directory into place
  command: cp -r {{ directory }}/tmp/{{ go_specific }}/go {{ directory }}/{{ go_version }}
  args:
    creates: "{{ directory }}/{{ go_version }}"
  become: yes
  become_user: "{{ user }}"

- git: repo=https://go.googlesource.com/go
       dest={{ directory }}/go
       update=yes
  become: yes
  become_user: "{{ user }}"

- name: Install go tip
  command: ./make.bash
  args:
    chdir: "{{ directory }}/go/src"
    creates: "{{ directory }}/go/bin/go"
  environment:
    GOROOT_BOOTSTRAP: "{{ directory }}/{{ go_version }}"
  become: yes
  become_user: "{{ user }}"

- lineinfile:
    dest: /home/go/.profile
    line: 'export GOPATH=/home/go'
    become: yes
    become_user: "{{ user }}"

- lineinfile:
    dest: /home/go/.profile
    line: 'export PATH=/home/go/bin:$PATH'
    become: yes
    become_user: "{{ user }}"
